-- Upsert verified business profiles for all users (dev/testing)
INSERT INTO public.business_profiles (
  user_id,
  business_name,
  business_type,
  business_description,
  verification_status,
  created_at,
  updated_at
)
SELECT 
  u.id,
  COALESCE(p.username, 'Business ' || substr(u.id::text, 1, 6)),
  'restaurant',
  'Autogenerated business profile for testing',
  'verified'::business_verification_status,
  now(),
  now()
FROM auth.users u
LEFT JOIN public.profiles p ON p.id = u.id
ON CONFLICT (user_id) DO UPDATE
SET verification_status = 'verified'::business_verification_status,
    updated_at = now();