// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrmklsvewmhpqixgyjmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhybWtsc3Zld21ocHFpeGd5am15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDEyODQsImV4cCI6MjA2NDM3NzI4NH0.fJQnWPsFLCZWfp6qWAPlYNsHX75g7lr6gA-WCXrFZqU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);